services:

    _defaults:
            autowire: true      # Automatically injects dependencies in your services.
            autoconfigure: true

    AgGridRowModel\:
        resource: '%kernel.project_dir%/vendor/tismaximo/ag-grid-row-model/src'
